# Generated by Django 5.1 on 2024-08-25 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='bo.medias'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='bo.medias'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='isRight',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='bo.medias'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bo.medias'),
        ),
        migrations.AlterField(
            model_name='medias',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medias',
            name='thumb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medias',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medias',
            name='variants',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bo.medias'),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bo.medias'),
        ),
    ]
