# Generated by Django 5.1 on 2024-08-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0002_alter_answers_audio_alter_answers_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='medias',
            name='thumb',
            field=models.FileField(null=True, upload_to='uploads/thumb/'),
        ),
    ]
